[build-system]
requires = ["setuptools >= 65", "wheel >= 0.38"]
build-backend = "setuptools.build_meta"

[project]
name = "tex_gen"
version = "0.4"
description = "Python package for LaTeX table and images generation"

[tool.setuptools]
py-modules = ["tex_gen"]